CREATE TABLE MEMBERS(
    ID VARCHAR2(30) NOT NULL,
    PW VARCHAR2(30) NOT NULL,
    NAME VARCHAR2(30) NOT NULL,
    EMAIL VARCHAR2(50)
);

ALTER TABLE MEMBERS ADD CONSTRAINT MEMBERS_PK PRIMARY KEY (ID);

SELECT * FROM MEMBERS;
